### ISSUE TITLE
Fix 32-bit golden image

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/cannolo#13]
'Te tocca' -cit.  
'Sì ma mo finemolo sto cannolo' -altra cit.

**Comment by morpheusthewhite** [comment]
Changing the virtualbox version may not be the solution, but further tests are needed.

Some problems encountered with our 32 golden image seems to be solved by upgrading the packages which did trigger a sort of GRUB repair (see image below) and the installation of some missing (maybe needed) packages (`--fix-install` was actually required by `apt`). 

So either those problems are caused by the missing packages or by the GRUB (which is very strange since 64 bits installation did not show any such problem). A quick solution, if working, could be to add an option to run this commands on the newly flashed disk

![IMG_20191210_171439](https://user-images.githubusercontent.com/36999173/70566285-0f0f6b80-1b94-11ea-9010-95fef0da3bae.jpg)

**Comment by morpheusthewhite** [comment]
From [VirtualBox site](https://www.virtualbox.org/wiki/Downloads)
```
Please also use version 5.2 if you still need support for 32-bit hosts, as this has been discontinued in 6.0. Version 5.2 will remain supported until July 2020. 
```

So this issue does not depend on the VirtualBox version

**Comment by e-caste** [comment]
@morpheusthewhite You can close this issue then

**Comment by morpheusthewhite** [comment]
I changed the title since the problem is not solved

**Comment by morpheusthewhite** [comment]
This seems to be solved with the new 32 bit golden image
