### ISSUE TITLE
Make golden image in OEM mode

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/cannolo#7]
When booting in Virtualbox, use F4 (or any working method) to choose OEM mode _before_ installing the system and making the needed changes (installing vlc, upgrading, etc...).

We can't use the golden image until this is done.

**Comment by morpheusthewhite** [comment]
This is the procedure I followed

1. I created a disk on VirtualBox with default size (10 GB), default type (`vdi`) but with fixed size (in this case the default option is dynamically allocated, but choosing that option will result in xubuntu formatting the disk with LVM, probably because it is easier to resize it in future). 
2. Install xubuntu according to instructions
3. Execute [pesca](https://github.com/WEEE-Open/pesca) on it
4. Comment or delete the line starting with `/swapfile`, since by default xubuntu creates a `swapfile`. 
5. Remove `/swapfile` (a reboot may be needed)

Then, to create the `.img` just run 
```bash
VBoxManage clonemedium --format RAW <file.vdi> <file.img>
```

**Comment by morpheusthewhite** [comment]
The process is the same for 32 bits images

**Comment by lvps** [comment]
@morpheusthewhite Nice

**Comment by e-caste** [comment]
@lvps Nice
